### PR TITLE
Feature/add download option to catalog

### PR DESCRIPTION
**Pull request by JJediny**

### CODE REVIEW

**Comment by JJediny** [comment]
@greensteph @afomi here is the current rendering for the PR:
image

Here is an alternative, placing it in the sidebar:
image

**Comment by afomi** [comment]
@JJediny - nice. 

Do the downloads provide ALL projects? or only filtered projects? 

That might influence where to put them.

**Comment by afomi** [comment]
assuming all projects (because yay data!), then, I'd try version A above, putting the buttons in the header.

I'd consider floating the buttons to the right of the `Number of Projects` and styling them if there's an equivalent of Bootstrap's `btn-sm` for USWDS. 
If not, Version A, as-is LGTM.

**Comment by JJediny** [comment]
@afomi yes both the csv/json dynamically include all projects as they are updated on the site from the yaml frontmatter from each project entry.

When I tried to put it inline with the Project count it didn't render well on mobile; and the secondary/small buttons all didnt work well with the page theme and layout. I'd prefer just to merge as is so we can add this to https://gsa.gov/data.json as a html/csv/json dataset once merged. thx!

**Comment by JohnMcLaughlinGSA** [comment]
Hi John,

     Thank you so much for this great addition to our.  We are currently lacking in time to give it the attention it deserves with a launch of the new Challenge.gov site and final preparations for tomorrow's U.S. Innovation Summit happening right now.  We will be in touch next week about it.

Thank you!

John McLaughlin

**Comment by saracope** [comment]
@JohnMcLaughlinGSA This looks good to merge. I reviewed the code and tested locally 👍

**Comment by JJediny** [comment]
@greensteph I've added the csv error you spotted, this should be ready to merge

**Comment by greensteph** [comment]
Looks good now. @jarahameador @JohnMcLaughlinGSA let me know when you are ready to merge.

**Comment by JohnMcLaughlinGSA** [comment]
Thank you @JJediny for making that fix! Thank you @greensteph and @saracope for the testing!  Stephanie, please make this exciting new feature live.

**Pull request merged**
